#!/bin/bash

NumberOfTests=$1
URL=$2
SleepDuration=$3
MaxTime=$4

#Check Vars
if [[ -z $1 ]] ; then NumberOfTests="10" ; fi
if [[ -z $2 ]] ; then URL="www.google.com" ; fi
if [[ -z $3 ]] ; then SleepDuration="0.250" ; fi

for ((i=1;i<=$NumberOfTests;i++))
do
        CurlTime=$(curl -X GET $URL --silent --output /dev/null -w "%{time_namelookup}")
        echo "$CurlTime"
        if [[ -n $MaxTime ]]; then
                if (( $(echo "$CurlTime > $MaxTime" | bc -l) )); then
                        exit 1
                fi
        fi
        sleep $SleepDuration
done

exit 0
